type GlistAPI = Window['glistAPI'];
export type EventMethod = Extract<keyof GlistAPI, `on${string}`>;
export type InvokeMethod = Exclude<keyof GlistAPI, EventMethod>;

// Arguments arrive untyped over IPC; each handler declares what it expects.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Handler = (...args: any[]) => unknown;
export type Handlers = Partial<Record<InvokeMethod, Handler>>;

// Every renderer call and the channel that carries it. The preload bridge and
// the browser transport are both generated from these tables.
export const invokeChannels: Record<InvokeMethod, string> = {
  windowProject: 'window:project',
  newWindow: 'window:new',
  quitApp: 'app:quit',
  copyText: 'app:copy-text',
  toggleDevTools: 'window:toggle-dev-tools',
  windowControl: 'window:control',
  windowMaximized: 'window:is-maximized',
  closeProject: 'window:close-project',
  openProject: 'project:open',
  createProject: 'project:create',
  listDirectory: 'project:list-directory',
  createFile: 'project:create-file',
  createDirectory: 'project:create-directory',
  deleteEntry: 'project:delete-entry',
  renameEntry: 'project:rename-entry',
  moveEntry: 'project:move-entry',
  createCppClass: 'project:create-cpp-class',
  copyEntry: 'project:copy-entry',
  importPaths: 'project:import-paths',
  importFiles: 'project:import-files',
  showInExplorer: 'project:show-in-explorer',
  readFile: 'project:read-file',
  readImage: 'project:read-image',
  readModel: 'project:read-model',
  openMedia: 'media:open',
  releaseMedia: 'media:release',
  databaseSchema: 'database:schema',
  databaseRows: 'database:rows',
  databaseQuery: 'database:query',
  databaseEdit: 'database:edit',
  databaseCommit: 'database:commit',
  databaseDiscard: 'database:discard',
  databaseClose: 'database:close',
  databaseStop: 'database:stop',
  databaseDiff: 'database:diff',
  databaseStamp: 'database:stamp',
  readWorkspaceFile: 'project:read-workspace-file',
  codeStyle: 'project:code-style',
  listDependencies: 'project:dependencies',
  searchText: 'project:search-text',
  listFiles: 'project:list-files',
  getProjectsDirectory: 'project:projects-directory',
  listProjects: 'project:list-projects',
  openProjectPath: 'project:open-path',
  getPlatform: 'app:platform',
  writeFile: 'project:write-file',
  buildProject: 'project:build',
  runProject: 'project:run',
  listTargets: 'project:list-targets',
  setTarget: 'project:set-target',
  stopProject: 'project:stop',
  setLanguage: 'settings:set-language',
  pathEntries: 'settings:path-entries',
  setCustomPath: 'settings:set-custom-path',
  setCustomEnvironment: 'settings:set-custom-environment',
  setRunArguments: 'settings:set-run-arguments',
  chooseFolder: 'settings:choose-folder',
  setTheme: 'settings:set-theme',
  setZoomFactor: 'view:set-zoom-factor',
  setAutoConfigure: 'build:auto-configure',
  terminalShells: 'terminal:shells',
  setTerminalShell: 'terminal:set-shell',
  setHiddenFolders: 'project:hidden-folders',
  openEngineSite: 'app:open-engine-site',
  openEngineRepository: 'app:open-engine-repository',
  startClangd: 'clangd:start',
  sendClangd: 'clangd:send',
  startDebugging: 'debug:start',
  sendDebug: 'debug:send',
  stopDebugging: 'debug:stop',
  debuggerStatus: 'debugger:status',
  installDebugger: 'debugger:install',
  startTerminal: 'terminal:start',
  writeTerminal: 'terminal:write',
  resizeTerminal: 'terminal:resize',
  stopTerminal: 'terminal:stop',
  listAgents: 'agents:list',
  glistStatus: 'glist:status',
  aboutInfo: 'app:about',
  debugInfo: 'app:debug-info',
  ping: 'repair:ping',
  restartBackend: 'repair:restart-backend',
  reloadWindow: 'repair:reload-window',
  repairState: 'repair:state',
  repairGit: 'repair:git',
  clearClangdIndex: 'repair:clear-clangd-index',
  setAppMenu: 'app:set-menu',
  listPlugins: 'plugins:list',
  checkPluginUpdates: 'plugins:check',
  installPlugin: 'plugins:install',
  updatePlugin: 'plugins:update',
  engineCheckout: 'engine:checkout',
  updateEngine: 'engine:update',
  usePlugin: 'plugins:use',
  pluginReadme: 'plugins:readme',
  startupSettings: 'app:startup-settings',
  setStartupSettings: 'app:set-startup-settings',
  updateState: 'update:state',
  checkForUpdates: 'update:check',
  installUpdate: 'update:install',
  openUpdatePage: 'update:open-page',
  rollbackChoices: 'update:rollback-choices',
  rollBack: 'update:roll-back',
  releaseHold: 'update:release-hold',
  installAgent: 'agents:install',
  gitStatus: 'git:status',
  gitWatch: 'git:watch',
  gitLog: 'git:log',
  gitUnpublished: 'git:unpublished',
  gitCommitDetails: 'git:commit-details',
  gitPatch: 'git:patch',
  gitBranches: 'git:branches',
  gitTags: 'git:tags',
  gitRemotes: 'git:remotes',
  gitStashes: 'git:stashes',
  gitFileAt: 'git:file-at',
  gitBlame: 'git:blame',
  gitIdentity: 'git:identity',
  gitLastMessage: 'git:last-message',
  gitOutgoing: 'git:outgoing',
  gitProtection: 'git:protection',
  gitRun: 'git:run',
  gitClone: 'git:clone',
};

export const eventChannels: Record<EventMethod, string> = {
  onBuildOutput: 'build:output',
  onBuildStatus: 'build:status',
  onConfigured: 'build:configured',
  onRunOutput: 'run:output',
  onRunStatus: 'run:status',
  onClangdMessage: 'clangd:message',
  onClangdStatus: 'clangd:status',
  onCompileCommands: 'clangd:compile-commands',
  onSaveAndClose: 'app:save-and-close',
  onBackendRestarted: 'app:backend-restarted',
  onDatabasesLost: 'database:lost',
  onAppError: 'app:error',
  onDebugMessage: 'debug:message',
  onDebugStatus: 'debug:status',
  onDebuggerInstall: 'debugger:install-output',
  onTerminalData: 'terminal:data',
  onTerminalExit: 'terminal:exit',
  onAgentInstall: 'agent:install',
  onUpdateState: 'update:changed',
  onGitChanged: 'git:changed',
  onGitConsole: 'git:console',
  onMenuCommand: 'app:menu-command',
  onWindowMaximized: 'window:maximized',
};
