import { getHostPlatform } from './host';
import { shortcutLabel } from './shortcuts';

export type Language = 'en' | 'tr';

const en = {
  menuFile: 'File', menuEdit: 'Edit', menuView: 'View', menuRun: 'Run', menuHelp: 'Help',
  openProject: 'Open Project', newProject: 'New Project', save: 'Save', build: 'Build', run: 'Run', stop: 'Stop',
  saveTitle: 'Save (Ctrl+S)', buildTitle: 'Build (Ctrl+Shift+B)', runTitle: 'Build and Run (F5)',
  stopTitle: 'Stop (Shift+F5)', settings: 'Settings', explorer: 'EXPLORER',
  buildRunControls: 'Build and run controls',
  newFile: 'New File', newFolder: 'New Folder', newCppClass: 'New C++ Class',
  newMenu: 'New', copy: 'Copy', paste: 'Paste', showIn: 'Show in',
  systemExplorer: 'System Explorer', commandPrompt: 'CMD',
  copied: 'Copied', pasted: 'Pasted', copyFailed: 'Could not copy item', showFailed: 'Could not open location',
  rename: 'Rename', delete: 'Move to Recycle Bin', deleteTitle: 'Move Selected Item to Recycle Bin',
  refresh: 'Refresh', projectPlaceholder: 'GLIST PROJECT', noFolder: 'No folder is open.',
  noFolderHint: 'Open an existing Glist project or create a new one.',
  openFolder: 'Open Folder', tagline: 'A focused development environment for Glist Engine.',
  output: 'OUTPUT', ready: 'Ready', clearOutput: 'Clear Output',
  closeExplorer: 'Close Explorer', closeOutput: 'Close Panel',
  terminal: 'TERMINAL', newTerminal: 'New Terminal', clearTerminal: 'Clear Terminal',
  dependencies: 'DEPENDENCIES',
  engineMissing: 'GlistEngine was not found two folders above the project, where the build looks for it.',
  pluginMissing: 'This plugin is named in CMakeLists.txt but is not in glistplugins, so the build will stop. Plugins can be downloaded from github.com/GlistPlugins.',
  agentTab: 'AGENT', restartAgent: 'Restart the Agent', clearAgent: 'Clear', agentChoice: 'Agent',
  agentExited: 'The agent exited with code', showAgent: 'Show Agent', hideAgent: 'Hide Agent',
  agents: 'Agents', agentInstall: 'Install', agentInstalling: 'Installing...', agentNotInstalled: 'Not installed',
  agentFromStudio: 'Installed in the Glist folder', agentFromGlist: 'Comes with Glist',
  agentFromSystem: 'Installed on this computer',
  agentInstallYourself: 'Not installed. Its own installer sets it up for the whole computer.',
  agentsHint: 'Coding assistants that work in the Agent tab, in the open project. Turn on the ones you want. One that is not installed can be installed here: it goes into the Glist folder, and nothing else on the computer changes.',
  terminalExited: 'The shell exited with code', terminalRestartHint: 'Press any key to start a new one.',
  initialOutput: 'Glist Studio is ready. Open a project to get started.',
  cancel: 'Cancel', create: 'Create', close: 'Close', template: 'Template',
  searchProjects: 'Search projects', browse: 'Browse...', neverOpened: 'Not opened yet', lastOpened: 'Opened {time}',
  noProjects: 'No projects here yet. Make one with New Project, or browse for a folder.',
  projectName: 'Project name', language: 'Language', appearance: 'Appearance',
  importTheme: 'Import a Theme File...', removeTheme: 'Remove',
  fonts: 'Fonts', codeFont: 'Code font', codeFontSize: 'Code size', interfaceFont: 'Interface font', systemFont: 'System',
  ligatures: 'Join characters such as => where the font supports it',
  fontsHint: 'Pick a font from the list or type the name of one installed on this computer.',
  themeImportFailed: 'This file is not a VS Code color theme.',
  languageHint: 'The interface language changes immediately.',
  themeHint: 'Themes color the whole studio. Color themes from VS Code (.json) can be imported.',
  undo: 'Undo', redo: 'Redo', find: 'Find', showExplorer: 'Show Explorer', hideExplorer: 'Hide Explorer',
  showOutput: 'Show Output', hideOutput: 'Hide Output', showTerminal: 'Show Terminal', hideTerminal: 'Hide Terminal', engineAbout: 'About Glist Engine',
  installGlist: 'Install Glist Engine', installGlistMenu: 'Install Glist Engine...', tryAgain: 'Try Again', stopInstall: 'Stop',
  openGlistApp: 'Open GlistApp', glistMissing: 'Glist Engine is not installed on this computer yet.',
  glistInstallIntro: 'This runs Glist Engine\'s own installer, the current one from github.com/GlistEngine/InstallScripts. It installs the compilers and libraries Glist needs, and puts the engine, an example app and the Glist tools in this folder. It downloads 1 to 2 GB.',
  installPasswordSystem: 'If it needs this computer\'s password, the system asks for it in a window of its own; Glist Studio never sees it.',
  installPasswordTerminal: 'If it needs this computer\'s password, type it in the terminal that appears below.',
  installStep: 'Step {step} of {total}: {name}', installStarting: 'Starting the installer...',
  glistInstalled: 'Glist Engine is installed.', glistInstallFailed: 'The installation stopped', exitCode: 'exit code',
  installStopped: 'stopped', confirmStopInstall: 'Stop the installation? What it has done so far stays, and installing again continues from there.',
  layout: 'Layout', zoom: 'Zoom', preferences: 'Preferences',
  zoomIn: 'Zoom In', zoomOut: 'Zoom Out', resetZoom: 'Reset Zoom',
  scale: 'Scale', scaleReset: 'Back to 100%', zoomInTitle: 'Zoom In (Ctrl++)', zoomOutTitle: 'Zoom Out (Ctrl+-)',
  resetZoomTitle: 'Back to 100% (Ctrl+0)',
  scaleHint: 'Makes everything in the studio larger or smaller, for example on a classroom projector.',
  fileName: 'File name', folderName: 'Folder name', className: 'Class name', newName: 'New name',
  openedProject: 'Project', noCmake: 'CMakeLists.txt was not found in this folder.',
  fileCreated: 'File created', folderCreated: 'Folder created', classCreated: 'C++ class created',
  projectCreated: 'Project created', movedToTrash: 'Moved to Recycle Bin', renamed: 'Renamed',
  createFailed: 'Could not create item', deleteFailed: 'Could not delete item', renameFailed: 'Could not rename item',
  fileOpenFailed: 'Could not open file', projectOpenFailed: 'Could not open project', treeFailed: 'Could not load files', saveFailed: 'Save failed',
  saved: 'saved', buildSucceeded: 'Build succeeded', buildFailed: 'Build failed',
  running: 'Application running', exit: 'Exit',
  confirmProjectSwitch: 'You have unsaved files. Open another project?',
  confirmClose: 'has unsaved changes. Close anyway?',
  confirmDeleteFile: 'Move this file to the Recycle Bin?',
  confirmDeleteFolder: 'Move this folder and all its contents to the Recycle Bin?',
  confirmDirtyDelete: 'Unsaved changes in this item will be lost. Continue?',
  classLocation: 'Select a folder for the C++ class.',
  open: 'Open',
  readOnly: 'Read-only', switchSourceHeader: 'Switch Header/Source', clangdRunning: 'is running',
  renameUnavailable: 'This symbol cannot be renamed.',
  editOutsideProject: 'The change touches files outside the project and was not applied.',
  debug: 'Debug', debugTitle: 'Debug (F6)', debugView: 'Run and Debug', startDebugging: 'Start Debugging',
  continue: 'Continue', continueTitle: 'Continue (F5)', pause: 'Pause',
  stepOver: 'Step Over', stepOverTitle: 'Step Over (F10)', stepInto: 'Step Into', stepIntoTitle: 'Step Into (F11)',
  stepOut: 'Step Out', stepOutTitle: 'Step Out (Shift+F11)', toggleBreakpoint: 'Toggle Breakpoint',
  breakpoint: 'Breakpoint', removeBreakpoint: 'Remove breakpoint',
  runAndDebug: 'RUN AND DEBUG', variables: 'VARIABLES', callStack: 'CALL STACK', breakpoints: 'BREAKPOINTS',
  noBreakpoints: 'Click to the left of a line number to stop there while debugging.',
  debugIdle: 'Debug runs your app so you can pause it, look at its variables, and go line by line.',
  debugStarting: 'Building for debugging and starting the debugger...',
  debugRunning: 'Running', debugPaused: 'Paused',
  programExited: 'The program exited with code', debuggerFailed: 'The debugger could not be started',
  gitSettings: 'Git',
  gitEnable: 'Show Git tools',
  gitHint: 'Adds a Commit view beside the explorer, a Git tab below the editor and the current branch to the title bar, and marks changed lines beside the line numbers. Projects stay as they are until you use them.',
  gitFound: 'Git {version} is installed.',
  gitNotFound: 'Git was not found on this computer. Install it from git-scm.com, then open Settings again.',
  gitName: 'Your name',
  gitEmail: 'Email',
  gitIdentityHint: 'Commits are signed with these, in every project on this computer.',
  gitUpdateMethod: 'Update Project brings in commits from the remote by',
  gitUpdateMerge: 'Merging them into the branch',
  gitUpdateRebase: 'Putting the branch\'s own commits after them (rebase)',
  commitView: 'COMMIT',
  commitViewTitle: 'Commit (Ctrl+K)',
  changes: 'Changes',
  unversioned: 'Unversioned Files',
  mergeConflicts: 'Merge Conflicts',
  noChanges: 'No changes since the last commit.',
  commitMessage: 'Commit message',
  commitMessageHint: 'What changed, and why (Ctrl+Enter commits)',
  amend: 'Amend the last commit',
  commit: 'Commit',
  commitAndPush: 'Commit and Push...',
  rollback: 'Rollback',
  rollbackTitle: 'Rollback Checked Files',
  confirmRollback: 'Put {count} files back as they were in the last commit? Your changes to them will be lost. Files that are new go to the trash.',
  confirmRollbackOne: 'Put {name} back as it was in the last commit? Your changes to it will be lost.',
  showDiff: 'Show Diff',
  openFile: 'Open File',
  addToGitignore: 'Add to .gitignore',
  showHistory: 'Show History',
  markResolved: 'Mark as Resolved',
  keepMine: 'Keep Mine',
  takeTheirs: 'Take Theirs',
  keepBoth: 'Keep Both',
  conflictHint: 'Open a file to choose change by change, or keep one side for the whole file.',
  noRepository: 'This project does not keep its history with Git yet.',
  noRepositoryHint: 'With a repository, you save versions of the project as commits, can go back to any of them, and can share the project.',
  createRepository: 'Create Git Repository',
  gitNoProject: 'Open a project to see its changes.',
  gitMissing: 'Git was not found on this computer. Install it from git-scm.com.',
  repositoryAt: 'Repository: {location}',
  merging: 'Merging: {subject}',
  rebasing: 'Rebasing {subject}',
  cherryPicking: 'Cherry-picking {subject}',
  reverting: 'Reverting {subject}',
  resolveThenCommit: 'Resolve the conflicts, then commit.',
  resolveThenContinue: 'Resolve the conflicts, then continue.',
  abort: 'Abort',
  skip: 'Skip',
  updateProject: 'Update Project',
  updateProjectTitle: 'Update Project (Ctrl+T)',
  push: 'Push...',
  pushTitle: 'Push (Ctrl+Shift+K)',
  fetch: 'Fetch',
  committedMessage: 'Committed: {subject}',
  stateModified: 'Modified',
  stateAdded: 'Added',
  stateDeleted: 'Deleted',
  stateRenamed: 'Renamed',
  stateUntracked: 'Unversioned',
  stateConflict: 'Conflict',
  stateTypechange: 'Type changed',
  stateIgnored: 'Ignored by Git',
  diffHead: 'Last commit ({hash})',
  diffWorking: 'Your version',
  diffCommit: 'Commit {hash}',
  diffMissing: 'Not in this version',
  diffBinary: 'This file is not text, so there are no lines to compare.',
  diffTooLarge: 'This file is too large to compare.',
  previousChange: 'Previous Change',
  nextChange: 'Next Change',
  toggleSideBySide: 'Side by Side or One Column',
  gitTab: 'GIT',
  gitLog: 'Log',
  gitBranches: 'Branches',
  gitRemotes: 'Remotes',
  gitStashes: 'Stashes',
  gitConsole: 'Console',
  allBranches: 'All branches',
  searchCommits: 'Search messages or hashes',
  historyOf: 'History of {name}',
  clearFilter: 'Show all history',
  noCommits: 'No commits yet.',
  selectCommit: 'Select a commit to see what it changed.',
  copyHash: 'Copy Revision Number',
  checkoutRevision: 'Checkout Revision',
  newBranch: 'New Branch...',
  newTag: 'New Tag...',
  cherryPick: 'Cherry-Pick',
  revertCommit: 'Revert Commit',
  resetHere: 'Reset Current Branch to Here...',
  resetTitle: 'Reset {branch} to {hash}',
  resetMixed: 'Keep the changes of the later commits, as changes not committed yet',
  resetSoft: 'Keep them, ready to be committed again',
  resetHard: 'Throw away the later commits and every change not committed',
  reset: 'Reset',
  confirmResetHard: 'Throw away the later commits and all changes not committed? This cannot be undone.',
  local: 'Local',
  remote: 'Remote',
  tags: 'Tags',
  checkout: 'Checkout',
  mergeInto: 'Merge into {branch}',
  rebaseOnto: 'Rebase {branch} onto This',
  deleteBranch: 'Delete',
  currentBranch: 'current',
  branchGone: 'gone from the remote',
  confirmDeleteBranch: 'Delete the branch {name}?',
  confirmForceDelete: '{name} has commits that are in no other branch. Delete it anyway? They will be lost.',
  confirmDeleteRemoteBranch: 'Delete {name} from the remote? Everyone using it loses it.',
  confirmDeleteTag: 'Delete the tag {name}?',
  branchName: 'Branch name',
  newBranchFrom: 'New branch from {start}',
  tagName: 'Tag name',
  tagMessage: 'Message (optional)',
  addRemote: 'Add Remote...',
  remoteName: 'Name',
  remoteUrl: 'URL',
  editRemote: 'Edit URL...',
  removeRemote: 'Remove',
  confirmRemoveRemote: 'Remove the remote {name} from this repository? Nothing on the remote itself is deleted.',
  noRemotes: 'No remotes yet. Add one to push the project somewhere, such as GitHub.',
  stashChanges: 'Stash Changes...',
  stashMessage: 'Message (optional)',
  stashUntracked: 'Include unversioned files',
  applyStash: 'Apply',
  popStash: 'Apply and Delete',
  dropStash: 'Delete',
  confirmDropStash: 'Delete {name}? The changes in it will be lost.',
  noStashes: 'Nothing is stashed. Stashing puts your changes aside, so you can work on something else and bring them back later.',
  clearConsole: 'Clear Console',
  gitRefresh: 'Refresh',
  pushCommits: 'Push Commits',
  pushTarget: '{branch} to {remote}',
  pushNothing: 'There are no commits to push.',
  pushNewBranch: 'The branch is new on the remote, and will follow it from now on.',
  pushTags: 'Push tags too',
  forcePush: 'Overwrite the remote branch (force push)',
  forcePushHint: 'Only for commits that were changed after they were pushed. Commits others pushed since would be lost.',
  pushButton: 'Push',
  remoteLabel: 'Remote',
  cloneMenu: 'Get from Git...',
  cloneTitle: 'Get from Git',
  cloneUrl: 'Repository URL',
  cloneLocation: 'It goes into {location}.',
  cloneButton: 'Clone',
  cloning: 'Cloning...',
  identityTitle: 'Who is committing?',
  identityHint: 'Git records a name and an email with each commit. They are kept for every project on this computer, and can be changed in Settings.',
  saveButton: 'Save',
  menuGit: 'Git',
  commitMenu: 'Commit...',
  pushMenu: 'Push...',
  branchesMenu: 'Branches...',
  gitLogMenu: 'Show Git Log',
  remotesMenu: 'Manage Remotes...',
  currentFile: 'Current File',
  annotate: 'Annotate with Git Blame',
  hideAnnotate: 'Close Annotations',
  localBranches: 'Local Branches',
  remoteBranches: 'Remote Branches',
  manageBranches: 'Manage Branches...',
  detached: 'Detached at {hash}',
  branchChipTitle: 'Git branch: {branch}',
  aheadBehind: '{ahead} to push, {behind} to update',
  pushedTo: 'Pushed to {target}.',
  updatedFrom: 'Updated from {upstream}.',
  fetched: 'Fetched.',
  checkedOut: 'Checked out {name}.',
  smartCheckout: 'Stash and Checkout',
  conflictsNotice: 'There are conflicts to resolve. They are listed in the Commit view.',
  showConflicts: 'Show',
  showConsole: 'Show Console',
  deleteAnyway: 'Delete Anyway',
  gitFailed: 'Git could not do this',
  committing: 'Committing...',
  pushing: 'Pushing...',
  updating: 'Updating...',
  fetching: 'Fetching...',
  gitWorking: 'Working...',
  rollbackChange: 'Rollback This Change',
  linesBefore: 'Before this change',
  linesAdded: 'These lines are new since the last commit.',
  notCommittedYet: 'Not committed yet',
  blameUnavailable: 'This file has no committed history yet.',
  mine: 'Mine',
  theirs: 'Theirs',
  showInLog: 'Show in Git Log',
  blameClick: 'Click the line number to show the commit in the Git log.',
  conflictsResolvedIn: 'Every conflict in {name} is resolved.',
  keptMine: '{name}: your version was kept.',
  confirmShared: '{name} is shared by every project that uses it, so this changes it for all of them. Continue?',
  engineAndPlugins: 'Engine and Plugins',
  updateDependencies: 'Update Engine and Plugins',
  confirmUpdateDependencies: 'Bring in the latest commits of {names} from their remotes? Every project that uses them gets the changes.',
  noDependencyUpstream: 'The engine and plugins here follow no remote branch, so there is nothing to update them from.',
  kindProject: 'project',
  kindEngine: 'engine',
  kindPlugin: 'plugin',
  repositoryChoice: 'Repository',
  pushedRepository: '{name}: pushed to {target}.',
  updatedRepository: '{name}: updated from {upstream}.',
  sharedChanges: 'Changes in {name}, which every project that uses it shares. They are committed to its own repository.',
  sharedEdit: '{name} is shared by every project that uses it, so saving changes it for all of them.',
  buildSettings: 'Build',
  autoConfigure: 'Configure again when CMake files change',
  autoConfigureHint: 'When CMakeLists.txt or another CMake file of the project, the engine or its plugins changes, CMake configures the project again a moment later, so code completion knows new files without a build.',
  tookTheirs: '{name}: their version was taken.',
} as const;

export type TranslationKey = keyof typeof en;

const tr: Record<TranslationKey, string> = {
  menuFile: 'Dosya', menuEdit: 'Düzen', menuView: 'Görünüm', menuRun: 'Çalıştır', menuHelp: 'Yardım',
  openProject: 'Proje Aç', newProject: 'Yeni Proje', save: 'Kaydet', build: 'Derle', run: 'Çalıştır', stop: 'Durdur',
  saveTitle: 'Kaydet (Ctrl+S)', buildTitle: 'Derle (Ctrl+Shift+B)', runTitle: 'Derle ve Çalıştır (F5)',
  stopTitle: 'Durdur (Shift+F5)', settings: 'Ayarlar', explorer: 'EXPLORER',
  buildRunControls: 'Derleme ve çalıştırma kontrolleri',
  newFile: 'Yeni Dosya', newFolder: 'Yeni Klasör', newCppClass: 'Yeni C++ Sınıfı',
  newMenu: 'Yeni', copy: 'Kopyala', paste: 'Yapıştır', showIn: 'Şurada Göster',
  systemExplorer: 'Sistem Gezgini', commandPrompt: 'CMD',
  copied: 'Kopyalandı', pasted: 'Yapıştırıldı', copyFailed: 'Öğe kopyalanamadı', showFailed: 'Konum açılamadı',
  rename: 'Yeniden Adlandır', delete: 'Geri Dönüşüm Kutusu’na Taşı', deleteTitle: 'Seçili Öğeyi Geri Dönüşüm Kutusu’na Taşı',
  refresh: 'Yenile', projectPlaceholder: 'GLIST PROJESİ', noFolder: 'Henüz bir klasör açılmadı.',
  noFolderHint: 'Mevcut bir Glist projesini açın veya yeni bir proje oluşturun.',
  openFolder: 'Klasör Aç', tagline: 'Glist Engine için odaklanmış geliştirme ortamı.',
  output: 'ÇIKTI', ready: 'Hazır', clearOutput: 'Çıktıyı Temizle',
  closeExplorer: 'Explorer’ı Kapat', closeOutput: 'Paneli Kapat',
  terminal: 'TERMİNAL', newTerminal: 'Yeni Terminal', clearTerminal: 'Terminali Temizle',
  dependencies: 'BAĞIMLILIKLAR',
  engineMissing: 'GlistEngine, derlemenin aradığı yerde, projenin iki klasör üstünde bulunamadı.',
  pluginMissing: 'Bu eklenti CMakeLists.txt içinde adı geçiyor ama glistplugins içinde yok, bu yüzden derleme duracak. Eklentiler github.com/GlistPlugins adresinden indirilebilir.',
  agentTab: 'AJAN', restartAgent: 'Ajanı Yeniden Başlat', clearAgent: 'Temizle', agentChoice: 'Ajan',
  agentExited: 'Ajan şu kodla kapandı:', showAgent: 'Ajanı Göster', hideAgent: 'Ajanı Gizle',
  agents: 'Ajanlar', agentInstall: 'Kur', agentInstalling: 'Kuruluyor...', agentNotInstalled: 'Kurulu değil',
  agentFromStudio: 'Glist klasörüne kurulu', agentFromGlist: 'Glist ile geliyor',
  agentFromSystem: 'Bu bilgisayarda kurulu',
  agentInstallYourself: 'Kurulu değil. Kendi kurulum programı onu tüm bilgisayar için kurar.',
  agentsHint: 'Açık projede, Ajan sekmesinde çalışan kodlama asistanları. İstediklerinizi açın. Kurulu olmayan bir ajan buradan kurulabilir: Glist klasörüne kurulur, bilgisayarda başka hiçbir şey değişmez.',
  terminalExited: 'Kabuk şu kodla kapandı:', terminalRestartHint: 'Yenisini başlatmak için bir tuşa basın.',
  initialOutput: 'Glist Studio hazır. Başlamak için bir proje açın.',
  cancel: 'İptal', create: 'Oluştur', close: 'Kapat', template: 'Şablon',
  searchProjects: 'Projelerde ara', browse: 'Göz At...', neverOpened: 'Henüz açılmadı', lastOpened: '{time} açıldı',
  noProjects: 'Burada henüz proje yok. Yeni Proje ile oluşturun ya da bir klasöre göz atın.',
  projectName: 'Proje adı', language: 'Dil', appearance: 'Görünüm',
  importTheme: 'Tema Dosyası İçe Aktar...', removeTheme: 'Kaldır',
  fonts: 'Yazı Tipleri', codeFont: 'Kod yazı tipi', codeFontSize: 'Kod boyutu', interfaceFont: 'Arayüz yazı tipi',
  systemFont: 'Sistem',
  ligatures: 'Yazı tipi destekliyorsa => gibi karakterleri birleştir',
  fontsHint: 'Listeden bir yazı tipi seçin ya da bu bilgisayarda kurulu olanın adını yazın.',
  themeImportFailed: 'Bu dosya bir VS Code renk teması değil.',
  languageHint: 'Arayüz dili hemen değişir.',
  themeHint: 'Temalar tüm stüdyoyu renklendirir. VS Code renk temaları (.json) içe aktarılabilir.',
  undo: 'Geri Al', redo: 'Yinele', find: 'Bul', showExplorer: 'Explorer’ı Göster', hideExplorer: 'Explorer’ı Gizle',
  showOutput: 'Çıktıyı Göster', hideOutput: 'Çıktıyı Gizle', showTerminal: 'Terminali Göster', hideTerminal: 'Terminali Gizle', engineAbout: 'Glist Engine Hakkında',
  installGlist: 'Glist Engine’i Kur', installGlistMenu: 'Glist Engine’i Kur...', tryAgain: 'Yeniden Dene', stopInstall: 'Durdur',
  openGlistApp: 'GlistApp’i Aç', glistMissing: 'Glist Engine bu bilgisayarda henüz kurulu değil.',
  glistInstallIntro: 'Bu, Glist Engine’in kendi kurulum programını, github.com/GlistEngine/InstallScripts adresindeki güncel sürümü çalıştırır. Glist’in ihtiyaç duyduğu derleyicileri ve kütüphaneleri kurar; motoru, örnek bir uygulamayı ve Glist araçlarını bu klasöre koyar. 1-2 GB indirir.',
  installPasswordSystem: 'Bu bilgisayarın parolası gerekirse, sistem onu kendi penceresinde sorar; Glist Studio parolayı hiç görmez.',
  installPasswordTerminal: 'Bu bilgisayarın parolası gerekirse, aşağıda açılan terminale yazın.',
  installStep: 'Adım {step}/{total}: {name}', installStarting: 'Kurulum programı başlatılıyor...',
  glistInstalled: 'Glist Engine kuruldu.', glistInstallFailed: 'Kurulum durdu', exitCode: 'çıkış kodu',
  installStopped: 'durduruldu', confirmStopInstall: 'Kurulum durdurulsun mu? Şimdiye kadar yapılanlar kalır; yeniden kurmak kaldığı yerden devam eder.',
  layout: 'Yerleşim', zoom: 'Yakınlaştırma', preferences: 'Tercihler',
  zoomIn: 'Yakınlaştır', zoomOut: 'Uzaklaştır', resetZoom: 'Yakınlaştırmayı Sıfırla',
  scale: 'Ölçek', scaleReset: '%100’e Dön', zoomInTitle: 'Yakınlaştır (Ctrl++)', zoomOutTitle: 'Uzaklaştır (Ctrl+-)',
  resetZoomTitle: '%100’e Dön (Ctrl+0)',
  scaleHint: 'Stüdyodaki her şeyi büyütür veya küçültür, örneğin sınıftaki bir projeksiyonda.',
  fileName: 'Dosya adı', folderName: 'Klasör adı', className: 'Sınıf adı', newName: 'Yeni ad',
  openedProject: 'Proje', noCmake: 'Bu klasörde CMakeLists.txt bulunamadı.',
  fileCreated: 'Dosya oluşturuldu', folderCreated: 'Klasör oluşturuldu', classCreated: 'C++ sınıfı oluşturuldu',
  projectCreated: 'Proje oluşturuldu', movedToTrash: 'Geri Dönüşüm Kutusu’na taşındı', renamed: 'Yeniden adlandırıldı',
  createFailed: 'Öğe oluşturulamadı', deleteFailed: 'Öğe silinemedi', renameFailed: 'Öğe yeniden adlandırılamadı',
  fileOpenFailed: 'Dosya açılamadı', projectOpenFailed: 'Proje açılamadı', treeFailed: 'Dosyalar yüklenemedi', saveFailed: 'Kaydetme başarısız',
  saved: 'kaydedildi', buildSucceeded: 'Derleme başarılı', buildFailed: 'Derleme başarısız',
  running: 'Uygulama çalışıyor', exit: 'Çıkış',
  confirmProjectSwitch: 'Kaydedilmemiş dosyalar var. Başka proje açılsın mı?',
  confirmClose: 'kaydedilmedi. Yine de kapatılsın mı?',
  confirmDeleteFile: 'Bu dosya Geri Dönüşüm Kutusu’na taşınsın mı?',
  confirmDeleteFolder: 'Bu klasör ve içindekiler Geri Dönüşüm Kutusu’na taşınsın mı?',
  confirmDirtyDelete: 'Bu öğedeki kaydedilmemiş değişiklikler kaybolacak. Devam edilsin mi?',
  classLocation: 'C++ sınıfı için bir klasör seçin.',
  open: 'Aç',
  readOnly: 'Salt okunur', switchSourceHeader: 'Başlık/Kaynak Dosyasına Geç', clangdRunning: 'çalışıyor',
  renameUnavailable: 'Bu sembol yeniden adlandırılamaz.',
  editOutsideProject: 'Değişiklik proje dışındaki dosyalara dokunuyor ve uygulanmadı.',
  debug: 'Hata Ayıkla', debugTitle: 'Hata Ayıkla (F6)', debugView: 'Çalıştır ve Hata Ayıkla',
  startDebugging: 'Hata Ayıklamayı Başlat',
  continue: 'Devam Et', continueTitle: 'Devam Et (F5)', pause: 'Duraklat',
  stepOver: 'Üzerinden Geç', stepOverTitle: 'Üzerinden Geç (F10)', stepInto: 'İçine Gir', stepIntoTitle: 'İçine Gir (F11)',
  stepOut: 'Dışına Çık', stepOutTitle: 'Dışına Çık (Shift+F11)', toggleBreakpoint: 'Kesme Noktası Ekle/Kaldır',
  breakpoint: 'Kesme noktası', removeBreakpoint: 'Kesme noktasını kaldır',
  runAndDebug: 'ÇALIŞTIR VE HATA AYIKLA', variables: 'DEĞİŞKENLER', callStack: 'ÇAĞRI YIĞINI', breakpoints: 'KESME NOKTALARI',
  noBreakpoints: 'Hata ayıklarken orada durmak için bir satır numarasının soluna tıklayın.',
  debugIdle: 'Hata ayıklama uygulamanızı çalıştırır; onu duraklatıp değişkenlerine bakabilir ve satır satır ilerleyebilirsiniz.',
  debugStarting: 'Hata ayıklama için derleniyor ve hata ayıklayıcı başlatılıyor...',
  debugRunning: 'Çalışıyor', debugPaused: 'Duraklatıldı',
  programExited: 'Program şu kodla çıktı:', debuggerFailed: 'Hata ayıklayıcı başlatılamadı',
  gitSettings: 'Git',
  gitEnable: 'Git araçlarını göster',
  gitHint: 'Explorer\'ın yanına bir Commit görünümü, düzenleyicinin altına bir Git sekmesi ve başlık çubuğuna geçerli dalı ekler; değişen satırları satır numaralarının yanında işaretler. Siz kullanana kadar projeler olduğu gibi kalır.',
  gitFound: 'Git {version} kurulu.',
  gitNotFound: 'Bu bilgisayarda Git bulunamadı. git-scm.com adresinden kurup Ayarlar\'ı yeniden açın.',
  gitName: 'Adınız',
  gitEmail: 'E-posta',
  gitIdentityHint: 'Commit\'ler bu bilgilerle imzalanır; bu bilgisayardaki tüm projelerde geçerlidir.',
  gitUpdateMethod: 'Projeyi Güncelle, uzak depodaki commit\'leri şöyle alır:',
  gitUpdateMerge: 'Dala birleştirerek (merge)',
  gitUpdateRebase: 'Dalın kendi commit\'lerini onların arkasına koyarak (rebase)',
  commitView: 'COMMIT',
  commitViewTitle: 'Commit (Ctrl+K)',
  changes: 'Değişiklikler',
  unversioned: 'Sürüm Dışı Dosyalar',
  mergeConflicts: 'Birleştirme Çakışmaları',
  noChanges: 'Son commit\'ten beri değişiklik yok.',
  commitMessage: 'Commit mesajı',
  commitMessageHint: 'Ne değişti, neden (Ctrl+Enter ile commit)',
  amend: 'Son commit\'i düzelt',
  commit: 'Commit',
  commitAndPush: 'Commit ve Gönder...',
  rollback: 'Geri Al',
  rollbackTitle: 'İşaretli Dosyaları Geri Al',
  confirmRollback: '{count} dosya son commit\'teki hâline döndürülsün mü? Onlardaki değişiklikleriniz kaybolur. Yeni dosyalar çöpe gider.',
  confirmRollbackOne: '{name} son commit\'teki hâline döndürülsün mü? Ondaki değişiklikleriniz kaybolur.',
  showDiff: 'Farkı Göster',
  openFile: 'Dosyayı Aç',
  addToGitignore: '.gitignore\'a Ekle',
  showHistory: 'Geçmişi Göster',
  markResolved: 'Çözüldü Olarak İşaretle',
  keepMine: 'Benimkini Tut',
  takeTheirs: 'Onlarınkini Al',
  keepBoth: 'İkisini de Tut',
  conflictHint: 'Değişiklik değişiklik seçmek için dosyayı açın ya da dosyanın tamamı için bir tarafı seçin.',
  noRepository: 'Bu proje geçmişini henüz Git ile tutmuyor.',
  noRepositoryHint: 'Bir depoyla projenin sürümlerini commit olarak kaydeder, istediğinize geri dönebilir ve projeyi paylaşabilirsiniz.',
  createRepository: 'Git Deposu Oluştur',
  gitNoProject: 'Değişikliklerini görmek için bir proje açın.',
  gitMissing: 'Bu bilgisayarda Git bulunamadı. git-scm.com adresinden kurabilirsiniz.',
  repositoryAt: 'Depo: {location}',
  merging: 'Birleştiriliyor: {subject}',
  rebasing: 'Rebase yapılıyor: {subject}',
  cherryPicking: 'Cherry-pick yapılıyor: {subject}',
  reverting: 'Tersine çevriliyor: {subject}',
  resolveThenCommit: 'Çakışmaları çözün, sonra commit edin.',
  resolveThenContinue: 'Çakışmaları çözün, sonra devam edin.',
  abort: 'Vazgeç',
  skip: 'Atla',
  updateProject: 'Projeyi Güncelle',
  updateProjectTitle: 'Projeyi Güncelle (Ctrl+T)',
  push: 'Gönder...',
  pushTitle: 'Gönder (Ctrl+Shift+K)',
  fetch: 'Getir',
  committedMessage: 'Commit edildi: {subject}',
  stateModified: 'Değiştirildi',
  stateAdded: 'Eklendi',
  stateDeleted: 'Silindi',
  stateRenamed: 'Yeniden adlandırıldı',
  stateUntracked: 'Sürüm dışı',
  stateConflict: 'Çakışma',
  stateTypechange: 'Türü değişti',
  stateIgnored: 'Git tarafından yok sayılıyor',
  diffHead: 'Son commit ({hash})',
  diffWorking: 'Sizin sürümünüz',
  diffCommit: 'Commit {hash}',
  diffMissing: 'Bu sürümde yok',
  diffBinary: 'Bu dosya metin değil, karşılaştırılacak satır yok.',
  diffTooLarge: 'Bu dosya karşılaştırmak için çok büyük.',
  previousChange: 'Önceki Değişiklik',
  nextChange: 'Sonraki Değişiklik',
  toggleSideBySide: 'Yan Yana veya Tek Sütun',
  gitTab: 'GIT',
  gitLog: 'Geçmiş',
  gitBranches: 'Dallar',
  gitRemotes: 'Uzak Depolar',
  gitStashes: 'Saklananlar',
  gitConsole: 'Konsol',
  allBranches: 'Tüm dallar',
  searchCommits: 'Mesajlarda veya hash\'lerde ara',
  historyOf: '{name} geçmişi',
  clearFilter: 'Tüm geçmişi göster',
  noCommits: 'Henüz commit yok.',
  selectCommit: 'Neleri değiştirdiğini görmek için bir commit seçin.',
  copyHash: 'Revizyon Numarasını Kopyala',
  checkoutRevision: 'Bu Revizyona Geç',
  newBranch: 'Yeni Dal...',
  newTag: 'Yeni Etiket...',
  cherryPick: 'Cherry-Pick',
  revertCommit: 'Commit\'i Tersine Çevir',
  resetHere: 'Geçerli Dalı Buraya Sıfırla...',
  resetTitle: '{branch} dalını {hash} commit\'ine sıfırla',
  resetMixed: 'Sonraki commit\'lerin değişikliklerini commit edilmemiş değişiklik olarak tut',
  resetSoft: 'Onları yeniden commit edilmeye hazır tut',
  resetHard: 'Sonraki commit\'leri ve commit edilmemiş her değişikliği at',
  reset: 'Sıfırla',
  confirmResetHard: 'Sonraki commit\'ler ve commit edilmemiş tüm değişiklikler atılsın mı? Bu geri alınamaz.',
  local: 'Yerel',
  remote: 'Uzak',
  tags: 'Etiketler',
  checkout: 'Geç',
  mergeInto: '{branch} dalına birleştir',
  rebaseOnto: '{branch} dalını buna göre rebase et',
  deleteBranch: 'Sil',
  currentBranch: 'geçerli',
  branchGone: 'uzak depodan silinmiş',
  confirmDeleteBranch: '{name} dalı silinsin mi?',
  confirmForceDelete: '{name} dalında başka hiçbir dalda olmayan commit\'ler var. Yine de silinsin mi? Onlar kaybolur.',
  confirmDeleteRemoteBranch: '{name} uzak depodan silinsin mi? Onu kullanan herkes için silinir.',
  confirmDeleteTag: '{name} etiketi silinsin mi?',
  branchName: 'Dal adı',
  newBranchFrom: '{start} noktasından yeni dal',
  tagName: 'Etiket adı',
  tagMessage: 'Mesaj (isteğe bağlı)',
  addRemote: 'Uzak Depo Ekle...',
  remoteName: 'Ad',
  remoteUrl: 'Adres',
  editRemote: 'Adresi Düzenle...',
  removeRemote: 'Kaldır',
  confirmRemoveRemote: '{name} uzak deposu bu depodan kaldırılsın mı? Uzak depodaki hiçbir şey silinmez.',
  noRemotes: 'Henüz uzak depo yok. Projeyi GitHub gibi bir yere göndermek için bir tane ekleyin.',
  stashChanges: 'Değişiklikleri Sakla...',
  stashMessage: 'Mesaj (isteğe bağlı)',
  stashUntracked: 'Sürüm dışı dosyaları da dahil et',
  applyStash: 'Uygula',
  popStash: 'Uygula ve Sil',
  dropStash: 'Sil',
  confirmDropStash: '{name} silinsin mi? İçindeki değişiklikler kaybolur.',
  noStashes: 'Saklanan bir şey yok. Saklamak değişikliklerinizi kenara koyar; başka bir şey üzerinde çalışıp onları sonra geri getirebilirsiniz.',
  clearConsole: 'Konsolu Temizle',
  gitRefresh: 'Yenile',
  pushCommits: 'Commit\'leri Gönder',
  pushTarget: '{branch} dalını {remote} deposuna',
  pushNothing: 'Gönderilecek commit yok.',
  pushNewBranch: 'Dal uzak depoda yeni; bundan sonra onu takip edecek.',
  pushTags: 'Etiketleri de gönder',
  forcePush: 'Uzak dalın üzerine yaz (force push)',
  forcePushHint: 'Yalnızca gönderildikten sonra değiştirilen commit\'ler için. Başkalarının o zamandan beri gönderdiği commit\'ler kaybolur.',
  pushButton: 'Gönder',
  remoteLabel: 'Uzak depo',
  cloneMenu: 'Git\'ten Al...',
  cloneTitle: 'Git\'ten Al',
  cloneUrl: 'Depo adresi',
  cloneLocation: '{location} içine konur.',
  cloneButton: 'Klonla',
  cloning: 'Klonlanıyor...',
  identityTitle: 'Commit\'i kim yapıyor?',
  identityHint: 'Git her commit\'le bir ad ve e-posta kaydeder. Bunlar bu bilgisayardaki tüm projeler için saklanır ve Ayarlar\'dan değiştirilebilir.',
  saveButton: 'Kaydet',
  menuGit: 'Git',
  commitMenu: 'Commit...',
  pushMenu: 'Gönder...',
  branchesMenu: 'Dallar...',
  gitLogMenu: 'Git Geçmişini Göster',
  remotesMenu: 'Uzak Depoları Yönet...',
  currentFile: 'Geçerli Dosya',
  annotate: 'Git Blame ile Satır Geçmişini Göster',
  hideAnnotate: 'Satır Geçmişini Kapat',
  localBranches: 'Yerel Dallar',
  remoteBranches: 'Uzak Dallar',
  manageBranches: 'Dalları Yönet...',
  detached: '{hash} commit\'inde (dal yok)',
  branchChipTitle: 'Git dalı: {branch}',
  aheadBehind: '{ahead} gönderilecek, {behind} güncellenecek',
  pushedTo: '{target} deposuna gönderildi.',
  updatedFrom: '{upstream} ile güncellendi.',
  fetched: 'Getirildi.',
  checkedOut: '{name} dalına geçildi.',
  smartCheckout: 'Saklayıp Geç',
  conflictsNotice: 'Çözülmesi gereken çakışmalar var. Commit görünümünde listelenirler.',
  showConflicts: 'Göster',
  showConsole: 'Konsolu Göster',
  deleteAnyway: 'Yine de Sil',
  gitFailed: 'Git bunu yapamadı',
  committing: 'Commit ediliyor...',
  pushing: 'Gönderiliyor...',
  updating: 'Güncelleniyor...',
  fetching: 'Getiriliyor...',
  gitWorking: 'Çalışıyor...',
  rollbackChange: 'Bu Değişikliği Geri Al',
  linesBefore: 'Bu değişiklikten önce',
  linesAdded: 'Bu satırlar son commit\'ten beri yeni.',
  notCommittedYet: 'Henüz commit edilmedi',
  blameUnavailable: 'Bu dosyanın henüz commit edilmiş geçmişi yok.',
  mine: 'Benim',
  theirs: 'Onların',
  showInLog: 'Git Geçmişinde Göster',
  blameClick: 'Commit\'i Git geçmişinde görmek için satır numarasına tıklayın.',
  conflictsResolvedIn: '{name} içindeki tüm çakışmalar çözüldü.',
  keptMine: '{name}: sizin sürümünüz tutuldu.',
  confirmShared: '{name}, onu kullanan tüm projelerce paylaşılıyor; bu, hepsi için değişir. Devam edilsin mi?',
  engineAndPlugins: 'Motor ve Eklentiler',
  updateDependencies: 'Motoru ve Eklentileri Güncelle',
  confirmUpdateDependencies: '{names} için uzak depolardaki son commit\'ler alınsın mı? Onları kullanan her proje bu değişiklikleri alır.',
  noDependencyUpstream: 'Buradaki motor ve eklentiler hiçbir uzak dalı takip etmiyor; güncellenecekleri bir yer yok.',
  kindProject: 'proje',
  kindEngine: 'motor',
  kindPlugin: 'eklenti',
  repositoryChoice: 'Depo',
  pushedRepository: '{name}: {target} deposuna gönderildi.',
  updatedRepository: '{name}: {upstream} ile güncellendi.',
  sharedChanges: '{name} içindeki değişiklikler; onu kullanan her proje bunları paylaşır. Kendi deposuna commit edilirler.',
  sharedEdit: '{name}, onu kullanan tüm projelerce paylaşılıyor; kaydetmek hepsi için değiştirir.',
  buildSettings: 'Derleme',
  autoConfigure: 'CMake dosyaları değişince yeniden yapılandır',
  autoConfigureHint: 'Projenin, motorun veya eklentilerinin CMakeLists.txt ya da başka bir CMake dosyası değişince, CMake projeyi kısa süre sonra yeniden yapılandırır; böylece kod tamamlama yeni dosyaları derlemeden tanır.',
  tookTheirs: '{name}: onların sürümü alındı.',
};

const dictionaries = { en, tr };

type Wording = Partial<Record<TranslationKey, string>>;

// Names the host gives its trash, file manager and terminal; the dictionaries
// above use the Windows ones.
const hostWording: Record<string, Record<Language, Wording>> = {
  darwin: {
    en: {
      delete: 'Move to Trash', deleteTitle: 'Move Selected Item to Trash', movedToTrash: 'Moved to Trash',
      confirmDeleteFile: 'Move this file to the Trash?',
      confirmDeleteFolder: 'Move this folder and all its contents to the Trash?',
      systemExplorer: 'Finder', commandPrompt: 'Terminal',
    },
    tr: {
      delete: 'Çöp Sepeti’ne Taşı', deleteTitle: 'Seçili Öğeyi Çöp Sepeti’ne Taşı', movedToTrash: 'Çöp Sepeti’ne taşındı',
      confirmDeleteFile: 'Bu dosya Çöp Sepeti’ne taşınsın mı?',
      confirmDeleteFolder: 'Bu klasör ve içindekiler Çöp Sepeti’ne taşınsın mı?',
      systemExplorer: 'Finder', commandPrompt: 'Terminal',
    },
  },
  linux: {
    en: {
      delete: 'Move to Trash', deleteTitle: 'Move Selected Item to Trash', movedToTrash: 'Moved to Trash',
      confirmDeleteFile: 'Move this file to the Trash?',
      confirmDeleteFolder: 'Move this folder and all its contents to the Trash?',
      systemExplorer: 'File Manager', commandPrompt: 'Terminal',
    },
    tr: {
      delete: 'Çöp Kutusu’na Taşı', deleteTitle: 'Seçili Öğeyi Çöp Kutusu’na Taşı', movedToTrash: 'Çöp Kutusu’na taşındı',
      confirmDeleteFile: 'Bu dosya Çöp Kutusu’na taşınsın mı?',
      confirmDeleteFolder: 'Bu klasör ve içindekiler Çöp Kutusu’na taşınsın mı?',
      systemExplorer: 'Dosya Yöneticisi', commandPrompt: 'Terminal',
    },
  },
};

export const savedLanguage = (): Language => {
  try { return window.localStorage.getItem('glist-studio-language') === 'tr' ? 'tr' : 'en'; }
  catch { return 'en'; }
};

let language: Language = savedLanguage();

export const getLanguage = (): Language => language;
export const t = (key: TranslationKey): string =>
  hostWording[getHostPlatform()]?.[language][key] ?? dictionaries[language][key];

export const applyLanguage = (next: Language): void => {
  language = next;
  try { window.localStorage.setItem('glist-studio-language', next); } catch { /* Storage may be unavailable. */ }
  document.documentElement.lang = next;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n as TranslationKey;
    if (key in en) node.textContent = t(key);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-title]').forEach((node) => {
    const key = node.dataset.i18nTitle as TranslationKey;
    if (key in en) node.title = shortcutLabel(t(key));
  });
  document.querySelectorAll<HTMLInputElement>('[data-i18n-placeholder]').forEach((node) => {
    const key = node.dataset.i18nPlaceholder as TranslationKey;
    if (key in en) node.placeholder = t(key);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-aria-label]').forEach((node) => {
    const key = node.dataset.i18nAriaLabel as TranslationKey;
    if (key in en) node.setAttribute('aria-label', t(key));
  });
  document.querySelectorAll('kbd').forEach((node) => { node.textContent = shortcutLabel(node.textContent ?? ''); });
};
